# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acbf3f888943c945f3e86fd565d7587024c80794de7e2810d49ea40fba1a97b3eefdb213b5a6987725697d0dc231e666777ce1fd6fa0d0c4e038ddfef208090c

test:
  secret_key_base: 461330f288355d3e96a108cf45c63407a200ff2217a33ef57efe24e97444295930db82651f3a5e5cf598007366df8799ac71e095c668887097b3847aa77982de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
